language: csharp
solution: "testapp.sln"
before_install:
  - wget https://www.dropbox.com/s/9b8rzmr27yv474b/Managed.tar.gz?dl=1 -O /tmp/Managed.tar.gz
  - mkdir -p /home/travis/build/krzychu124/testapp/managed && tar -xzvf /tmp/Managed.tar.gz -C /home/travis/build/krzychu124/testapp/managed
script:
  - msbuild /p:Configuration=Release /p:TreatWarningsAsErrors="true" testapp.sln 
branches:
  only:
    - master
notifications:
  - email: false 