language: csharp
solution: "testapp.sln"
before_install:
  - cd /tmp && curl -L -o Dependencies.tar.gz $DEPENDENCIES_URL 
  - mkdir -p /home/travis/build/krzychu124/testapp/managed && tar -xzf /tmp/Dependencies.tar.gz -C /home/travis/build/krzychu124/testapp/managed
  - cd krzychu124/testapp
script:
  - msbuild /p:Configuration=Release /p:TreatWarningsAsErrors="true" /p:PostBuildEvent= testapp.sln 
branches:
  only:
    - master
notifications:
  - email: false 